"""Add telegram_photo to User db model

Revision ID: 4a0ff436d00b
Revises: e9a8cb911f66
Create Date: 2025-05-23 20:08:33.343320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a0ff436d00b'
down_revision: Union[str, None] = 'e9a8cb911f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_photo')
    # ### end Alembic commands ###
