"""Add Lake postgis

Revision ID: 3b075588bc21
Revises: 2074c1438361
Create Date: 2025-05-06 14:58:39.875420

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b075588bc21'
down_revision: Union[str, None] = '2074c1438361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('lakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('''
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename = 'lakes' AND indexname = 'idx_lakes_geom') THEN
                CREATE INDEX idx_lakes_geom ON lakes USING gist (geom);
            END IF;
        END
        $$;
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE tablename = 'lakes' AND indexname = 'idx_lakes_geom') THEN
                DROP INDEX idx_lakes_geom;
            END IF;
        END
        $$;
    ''')
    op.drop_table('lakes')
    # ### end Alembic commands ###
