"""Remove location fields from User & Report models

Revision ID: 64624459ed6e
Revises: 830da0adb079
Create Date: 2025-05-07 19:46:52.073537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64624459ed6e'
down_revision: Union[str, None] = '830da0adb079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_region', table_name='reports')
    op.drop_column('reports', 'location')
    op.drop_column('reports', 'region')
    op.drop_column('reports', 'search_radius')
    op.drop_index('ix_users_region', table_name='users')
    op.drop_column('users', 'geo_longitude')
    op.drop_column('users', 'geo_latitude')
    op.drop_column('users', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('geo_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('geo_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_users_region', 'users', ['region'], unique=False)
    op.add_column('reports', sa.Column('search_radius', sa.INTEGER(), server_default=sa.text('5000'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_reports_region', 'reports', ['region'], unique=False)
    # ### end Alembic commands ###
