"""Add Notification model

Revision ID: 0f05d578b506
Revises: 7321cb77045f
Create Date: 2025-05-17 01:30:24.173192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f05d578b506'
down_revision: Union[str, None] = '7321cb77045f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('method', sa.String(), nullable=True),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.Column('recipient_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('report_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_report_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
