"""Upd Notification model to add BigInteger for recipients ids

Revision ID: e9a8cb911f66
Revises: 0f05d578b506
Create Date: 2025-05-23 18:59:06.888086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9a8cb911f66'
down_revision: Union[str, None] = '0f05d578b506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'recipient_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'recipient_ids',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=False)
    # ### end Alembic commands ###
