"""Add celery reminder tasks ids to Pet model

Revision ID: 58a04e181609
Revises: 4a0ff436d00b
Create Date: 2025-06-03 01:14:48.580570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a04e181609'
down_revision: Union[str, None] = '4a0ff436d00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('vaccination_reminder_task_id', sa.String(length=255), nullable=True))
    op.add_column('pets', sa.Column('parasite_reminder_task_id', sa.String(length=255), nullable=True))
    op.add_column('pets', sa.Column('fleas_ticks_reminder_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'fleas_ticks_reminder_task_id')
    op.drop_column('pets', 'parasite_reminder_task_id')
    op.drop_column('pets', 'vaccination_reminder_task_id')
    # ### end Alembic commands ###
