"""Change Geometry to Geography to calculate in metres

Revision ID: 7321cb77045f
Revises: 64624459ed6e
Create Date: 2025-05-11 01:32:30.936257

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7321cb77045f'
down_revision: Union[str, None] = '64624459ed6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'geolocations',
        'home_location',
        existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326),
        type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326),
        existing_nullable=True
    )
    op.alter_column(
        'geolocations',
        'polygon',
        existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326),
        type_=geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'geolocations',
        'home_location',
        existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326),
        type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326),
        existing_nullable=True
    )
    op.alter_column(
        'geolocations',
        'polygon',
        existing_type=geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326),
        type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326),
        existing_nullable=True
    )
    # ### end Alembic commands ###
