"""Save pets/reports after User deleting & save reports after Pet deleting

Revision ID: 1cc4b59ad90e
Revises: 4a0ff436d00b
Create Date: 2025-06-06 01:22:09.285668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cc4b59ad90e'
down_revision: Union[str, None] = '4a0ff436d00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_report_id'), 'notifications', ['report_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.drop_constraint(op.f('reportphotos_report_id_fkey'), 'reportphotos', type_='foreignkey')
    op.create_foreign_key(None, 'reportphotos', 'reports', ['report_id'], ['id'])
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reports', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('reports_user_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_pet_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'pets', ['pet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_pet_id_fkey'), 'reports', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reports_user_id_fkey'), 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reports', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'reportphotos', type_='foreignkey')
    op.create_foreign_key(op.f('reportphotos_report_id_fkey'), 'reportphotos', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
